"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class marker_t(object):
    __slots__ = ["name", "xyz", "o"]

    def __init__(self):
        self.name = ""
        self.xyz = [ 0.0 for dim0 in range(3) ]
        self.o = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(marker_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack('>3d', *self.xyz[:3]))
        buf.write(struct.pack(">d", self.o))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != marker_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return marker_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = marker_t()
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.xyz = struct.unpack('>3d', buf.read(24))
        self.o = struct.unpack(">d", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if marker_t in parents: return 0
        tmphash = (0x48da563fb6fca07c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if marker_t._packed_fingerprint is None:
            marker_t._packed_fingerprint = struct.pack(">Q", marker_t._get_hash_recursive([]))
        return marker_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

