"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import vicon.segment_t

import vicon.marker_t

class model_t(object):
    __slots__ = ["name", "nummarkers", "numsegments", "markers", "segments"]

    def __init__(self):
        self.name = ""
        self.nummarkers = 0
        self.numsegments = 0
        self.markers = []
        self.segments = []

    def encode(self):
        buf = BytesIO()
        buf.write(model_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">ii", self.nummarkers, self.numsegments))
        for i0 in range(self.nummarkers):
            assert self.markers[i0]._get_packed_fingerprint() == vicon.marker_t._get_packed_fingerprint()
            self.markers[i0]._encode_one(buf)
        for i0 in range(self.numsegments):
            assert self.segments[i0]._get_packed_fingerprint() == vicon.segment_t._get_packed_fingerprint()
            self.segments[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != model_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return model_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = model_t()
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.nummarkers, self.numsegments = struct.unpack(">ii", buf.read(8))
        self.markers = []
        for i0 in range(self.nummarkers):
            self.markers.append(vicon.marker_t._decode_one(buf))
        self.segments = []
        for i0 in range(self.numsegments):
            self.segments.append(vicon.segment_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if model_t in parents: return 0
        newparents = parents + [model_t]
        tmphash = (0xf9e590c6ee408643+ vicon.marker_t._get_hash_recursive(newparents)+ vicon.segment_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if model_t._packed_fingerprint is None:
            model_t._packed_fingerprint = struct.pack(">Q", model_t._get_hash_recursive([]))
        return model_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

