"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import vicon.model_t

class vicon_t(object):
    __slots__ = ["utime", "nummodels", "models"]

    def __init__(self):
        self.utime = 0
        self.nummodels = 0
        self.models = []

    def encode(self):
        buf = BytesIO()
        buf.write(vicon_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.nummodels))
        for i0 in range(self.nummodels):
            assert self.models[i0]._get_packed_fingerprint() == vicon.model_t._get_packed_fingerprint()
            self.models[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != vicon_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return vicon_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = vicon_t()
        self.utime, self.nummodels = struct.unpack(">qi", buf.read(12))
        self.models = []
        for i0 in range(self.nummodels):
            self.models.append(vicon.model_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if vicon_t in parents: return 0
        newparents = parents + [vicon_t]
        tmphash = (0xed75eb26d3b4ea9f+ vicon.model_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if vicon_t._packed_fingerprint is None:
            vicon_t._packed_fingerprint = struct.pack(">Q", vicon_t._get_hash_recursive([]))
        return vicon_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

